services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    env_file:
      - .env
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: backend_container
    env_file:
      - ./backend/.env # aquí cargas tu .env local para el backend con las keys de OpenAI
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/${MYSQL_DATABASE}
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}

  frontend:
    build: ./frontend
    container_name: frontend_container
    env_file:
      - ./frontend/.env
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  mysql_data:
